### ISSUE TITLE
TV Tuner Demo

### ISSUE THREAD

**Issue by jmpicoto** [visioforge/.Net-SDK-s-samples#12]
I needed to use the Video Capture feature with TV Tuner input. It turns out that when testing the demo available, I can't receive a signal from the TV. Has this feature been deprecated or am I doing something wrong?
I'm using the demo:
TV Tuner Demo CLI (NuGet) net472

I'm using a coaxial cable to an AverMedia pen (AVerTV Hybrid Volard HD)

**Comment by visioforge** [comment]
Hi. Not deprecated, but not really popular :)

Do you want to record analog TV?

**Comment by jmpicoto** [comment]
Hello. Oh okay, i also assumed that
Yes. It would be to take that signal and transmit it on another platform. This was working before with your software and AverMedia hardware but it has stopped working and I'm trying to figure out why.
In your demo, it identifies the pen as a TV tuning signal but then fails to transmit it.
Here is a screenshot of my input. In the end, it just gives "rain noises"
https://ibb.co/D1t1SxY

**Comment by visioforge** [comment]
Please check TV tuning in the main demo - https://github.com/visioforge/.Net-SDK-s-samples/tree/master/Video%20Capture%20SDK/WinForms/CSharp/Main%20Demo

**Comment by jmpicoto** [comment]
https://ibb.co/ZJr1nJH


After using the main demo, this is the error it gives me. I have also tried all the other options and nothing works to get the TV signal.

Here are two pictures with the connection I'm making to get the signal

https://ibb.co/ZdgP7PP
https://ibb.co/1RsfX1W

PS: thank you for taking the time to help me

**Comment by visioforge** [comment]
You told that you want analog TV. Is it analog TV or some DVB-T/DVB-C/ATSC?

In a Main Demo you've chosen DVB-x.

**Comment by jmpicoto** [comment]
It's analog TV. But there is no such option. Or at least, I don't know what it is. Anyway, I tried them all

**Comment by visioforge** [comment]
Yes, you need to use VideoPreview mode. You can set TV Tuner on video input and tv tuner tabs and start playback. When playback is started, you can tune channels.

**Comment by jmpicoto** [comment]
oh okay. So from my understanding, the problem is really in the AverMedia pen. Because even two tabs appear when I put it in VideoPreview mode (my webcam and a black page) and I suppose that the black page is the signal from the AverMedia pen. I hear White noise

**Comment by jmpicoto** [comment]
Do you have any recommendations for an analog signal converter for the PC that is compatible with your software?

**Comment by visioforge** [comment]
I'm not sure about a problem.

Can I connect to your PC using AnyDesk to help? You can send me credentials to support@visioforge.com .

**Comment by jmpicoto** [comment]
Yes. It's a good idea. Can we complement this with a call?

**Comment by visioforge** [comment]
Yes. Can it be tomorrow at 11AM GMT+1 time (Spain)? Please respond privately.

**Comment by visioforge** [comment]
Problem has been resolved in v15.5.37. 

Updated samples - https://github.com/visioforge/.Net-SDK-s-samples

**Comment by jmpicoto** [comment]
Even using version 15.5.37 the television transmission still does not work

**Comment by visioforge** [comment]
Can you tune channels in the updated Main Demo WPF or WinForms?

**Comment by jmpicoto** [comment]
I am using the Demo WPF in net5
In the video Input the signal button return this
https://ibb.co/nnrXVJ4
And if i try to tune channels this is the response
https://ibb.co/996tXn4
And no channels are detected

**Comment by visioforge** [comment]
Please send me a private message like before. Maybe I can connect AnyDesk again and try to help.

**Comment by jmpicoto** [comment]
Check Email

**Comment by visioforge** [comment]
OK, this issue is closed because looks that this issue is resolved. An issue can be reopened if we'll have this problem with alternative devices.

**Comment by jmpicoto** [comment]
hi.
I have news about this issue.
I have send you an email

**Comment by visioforge** [comment]
Yes, I've replied. I can confirm the DVB-C issue. This issue is closed because it's not about DVB-C.
